### ISSUE TITLE
picker selection

### ISSUE THREAD

**Issue by TDato** [nitric0/Tiply_v0.1#1]
The pickers don't default select the first row or option available. You have to select a different option and go back to the first one for it to register it. This becomes a real problem when there is only one person available for itemization.

**Comment by nitric0** [comment]
I think the way the picker works with an empty list -> 1 item is you have to move the picker up or down and then it will auto select the person if the list only had one person

**Comment by nitric0** [comment]
Added condition to have only person always show up automatically when picker field is pressed
